require("lspkind").init({
  mode = 'symbol_text',
  preset = 'codicons',
  symbol_map = {
    Text = "T",
    Method = "m",
    Function = "fx",
    Constructor = "",
    Field = "f",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "P",
    Unit = "U",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "R",
    Folder = "",
    EnumMember = "",
    Constant = "K",
    Struct = "",
    Event = "",
    Operator = "+",
    TypeParameter = "",
  },
})
